### ISSUE TITLE
Export IIS metrics to prometheus pushgateway

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1000]
Currently IIS execution report including various metrics is generated during IIS exporting phase and is made available as JSON file and via the oozie API after IIS workflow is completed.

One problem with this approach is the fact we need to wait until IIS finishes its job to know the metrics and potentially to spot anomalies. Some problems could be spotted at pretty early stage, e.g. during IIS import, so it would be reasonable to export metrics as soon as they were generated to avoid losing precious time.

We could take advantage of already existing prometheus and grafana instances to gather and present IIS metrics. Prometheus push gateway was already deployed and is ready to be used by IIS workflows. Having IIS hooked up with prometheus would expand whole new set of capabilities such as spotting regression based on an insight into the history of IIS executions, alerting, graphical presentation etc.

Since each module already covered with reporting functionality produces HDFS datastore holding [`ReportEntry`](https://github.com/openaire/iis/blob/master/iis-schemas/src/main/avro/eu/dnetlib/iis/common/ReportEntry.avdl) avro records we could quite easily provide generic action relying on those records (coming from one or more modules) and sending them to prometheus push gateway. In the first iteration we could place such action after each IIS main phase: import, processing, export. This way we could e.g. spot import related anomalies just after import phase finishes. Later on we could consider introducing more exporting checkpoints what will result in decreasing the delay between metrics generation time and their availability in prometheus.

We should agree on a naming convention of exported metrics, probably by relying on current report entry name, taking an environment into account (beta vs production, we could rely on user name triggering IIS job: either `dnet.beta` or `dnet.production`). Also report entry type (`counter` or `duration`) could be distinguished.

New solution should be implemented and defined in `iis-wf-report` module and it should be extremely fault tolerant (any error during pushing the results to pushgateway should not result in job interruption). Already implemented reporting mechanism could be still operating alongside.

**Comment by przemyslawjacewicz** [comment]
For reference purposes - this issue was covered with two pull requests: 
1. #1072 - addition of pushing to prometheus pushgateway 
1. #1081 - report entries keys name changes to allow for better creation of labels for common metrics
