### ISSUE TITLE
Remove unused dnet dependencies

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1066]
While working on #1045 and #1051 I have noticed several dependencies which seem to be unused and could be removed. 

Those two:
* `dnet-openaire-data-protos`
* `dnet-actionmanager-common`

including an old Oaf model and classes related to an old actionmanager service were removed as a part of #1065 pull request (introducing exporter module refactoring: #1045) but there are still some libs which could potentially be removed:
* `cnr-rmi-api` (according to `pom.xml` comments: MDStore related which is not used anymore)
* `cnr-service-utils` (according to `pom.xml` comments: MDStore related which is not used anymore)
* `cnr-resultset-client` (ResultSet related, need to check whether we still need this)
* `xalan` (seem to be related to an old export procedure requiring XML transformation)

which are not related to Oaf model refactoring so it should be considered as a separate task.

**Comment by marekhorst** [comment]
There is one another dnet dependency, `dnet-openaireplus-mapping-utils`, which is used only in a limited scope so we could consider removing it after getting rid of the following references:
* `eu.dnetlib.data.transform.xml.AbstractDNetXsltFunctions#md5()`
* `eu.dnetlib.data.transform.xml.AbstractDNetXsltFunctions#oafId()`
* `eu.dnetlib.openaire.exporter.model.ProjectDetail`

If it turns out to require too much effort we could leave it as it is.

**Comment by przemyslawjacewicz** [comment]
The list of removed dependencies
* `dnet-openaireplus-mapping-utils`
* `cnr-rmi-api`
* `cnr-service-utils`
* `xalan`

`cnr-resultset-client` is used and its usage is not easily replacable, so I'm leaving it.
