### ISSUE TITLE
Decrease number of output files produced for reports

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1071]
This task is similar to #923.

The number of files generated for reports can be unnecessary large with only single file containing the results. Due to the small amount of generated report entries we can decrease the number of files to a single file.

The reports with large number of files, indicated as subdirs in main `report` dir
* import_patent
* aff-matching
* affmatching-dedup
* citationmatching_direct
* citationmatching_fuzzy
* document_classification
* document_to_community_by_root_conceptid
* document_to_concept_by_root_conceptid
* document_to_project_by_funder
* project-based-docorg-matching
* referenceextraction_software
* export_software

**Comment by marekhorst** [comment]
For the record: we could limit the number of emitted files to 1 in all spark modules by applying `.coalesce(1)` on an RDD holding `ReportEntry` records.

We could apply this simple fix on all the spark modules producing reports.

**Comment by przemyslawjacewicz** [comment]
As investigated in #1103 a simple `coalesce(1)` can impact the number of tasks upstream so the solution is to force a repartition, either by `repartition(1)` or `coalesce(1, true)`.
