### ISSUE TITLE
Investigate the impact of setting the number of emitted files on jobs performance

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1103]
Many IIS workflows limit the number of files created when saving datastores to HDFS. The initial motivation for this behavior was to not allow the file number to grow beyond reasonable size when unioning with other datastores. In spark jobs the limit of created files is achieved by using `coalesce` with desired number of files as argument. This however has an effect on the number of tasks spawned in the stage performing the actual write - the number of tasks is limited by the number of files to be created. This behavior can hit the performance if the number of tasks is low and does not utilize the cluster properly.

The main purpose of this task is to find the workflows limiting the number of emitted files and investigate the impact of the number of files on job performance.

**Comment by marekhorst** [comment]
> This however has an effect on the number of tasks spawned in the stage performing the actual write - the number of tasks is limited by the number of files to be created.

This gave me this recollection regarding the TARA mining: probably the number of the tasks executing the madis is equal to the number of partitions provided as `coalesce()` parameter because the execution plan bound madis execution and write operations together in a single stage. If it was at different stage the number of madis tasks would probably differ from the number of output files.

**Comment by przemyslawjacewicz** [comment]
Yes, that's right. Pipe description says
```
With pipe, you can return an RDD created by piping elements to a forked external process. The resulting RDD is computed by executing the given process once per partition. All elements of each input partition are written to a process’s stdin as lines of input separated by a newline. The resulting partition consists of the process’s stdout output, with each line of stdout resulting in one element of the output partition. A process is invoked even for empty partitions.
```
So there is a one-to-one correspondence between number of tasks and number of partitions running madis. Because coalesce was pipelined into the same stage as madis execution the number of output files ultimately sets the number of tasks running madis.

**Comment by marekhorst** [comment]
OK, I think I have finally found the solution. In `coalesce()` method documentation:

https://spark.apache.org/docs/2.4.0/api/python/pyspark.sql.html#pyspark.sql.DataFrame.coalesce

and:

https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/RDD.scala#L494

one can read:

> However, if you’re doing a drastic coalesce, e.g. to numPartitions = 1, this may result in your computation taking place on fewer nodes than you like (e.g. one node in the case of numPartitions = 1). To avoid this, you can call repartition(). This will add a shuffle step, but means the current upstream partitions will be executed in parallel (per whatever the current partitioning is).

Some interesting remarks are also available in those posts:
https://stackoverflow.com/a/57112394
https://stackoverflow.com/a/57111852

So the solution is to replace `coalesce(numPartitions)` with either `coalesce(numPartitions, true)` or `repartition(numPartitions)` to make sure the limited number of files to be emitted does not affect the operations being executed upstream.
