### ISSUE TITLE
Update Jenkinsfiles for building and testing of IIS

### ISSUE THREAD

**Issue by openaire-devs** [openaire/iis#1113]
The goal of this issue is to update Jenkinsfile for building IIS in Jenkins and integration with GitHub.

Existing Jenkinsfile builds and runs unit tests, with additional configuration allowing to push build status to GitHub. It does not integrate with sonar and does not notify developers of failed builds.

**Comment by przemyslawjacewicz** [comment]
The following wiki pages contain the descriptions for creating Jenkins jobs from respective Jenkinsfiles:
* build and unit test with GitHub integration - [Jenkins and GitHub integration](https://github.com/openaire/iis/wiki/Jenkins-and-GitHub-integration)
* running integration tests - [Integration tests by Jenkins](https://github.com/openaire/iis/wiki/Integration-tests-by-Jenkins)
* deployment to HDFS - [Deployment by Jenkins](https://github.com/openaire/iis/wiki/Deployment-by-Jenkins) 

I've created three Jenkins jobs for testing and development
* [pj_iis_build_multibranch](http://ci.ceon.pl/view/IIS/job/pj_iis_build_multibranch/)
* [pj_iis_integration_tests](http://ci.ceon.pl/view/IIS/job/pj_iis_integration_tests/)
* [pj_iis_deployment](http://ci.ceon.pl/view/IIS/job/pj_iis_deployment/)
