### ISSUE TITLE
Refine affiliation matching rules and adjust the confidence level

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1129]
We should refine the affiliation matching rules and adjust the confidence level whenever matching against organizations is lacking the metadata details.

There were two unrelated issues reported on redmine:
https://issue.openaire.research-infrastructures.eu/issues/4892
https://issue.openaire.research-infrastructures.eu/issues/5624

where at least part of the problem was bound to a relatively high confidence level when matching organizations by either relying on short organization name alone ("NLR" case) or on a pretty generic organization full name alone ("Institute of Physics" case). We should calibrate the confidence level for such cases.

**Comment by marekhorst** [comment]
One another report:
https://issue.openaire.research-infrastructures.eu/issues/5909

related to already reported issue:
https://issue.openaire.research-infrastructures.eu/issues/4892

**Comment by marekhorst** [comment]
Apparently our customers are asking when this problem is going to be fixed, so we should bump the priority and make this task part of the next sprint round.

**Comment by marekhorst** [comment]
We should also remove the untrustworthy matches in exporter module:

https://issue.openaire.research-infrastructures.eu/issues/5909#note-14

**Comment by przemyslawjacewicz** [comment]
For reference: this is a parent task for all tasks in 'Affiliation matching refinement' project.
