### ISSUE TITLE
Reduce integration tests execution time by decreasing the number of partitions

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1161]
As already indicated in https://github.com/openaire/iis/pull/1160#pullrequestreview-498206163 PR comment it seems we could decrease the number of partitions when running integration tests.

In some places (including webcrawling in software reference extraction) we have 1000 partitions defined what results in running 1000 tasks. It takes 10 minutes to process them on our test cluster because the computational resources are very limited. I guess we could decrease the number of partitions by overriding it in test workflow definition.

**Comment by marekhorst** [comment]
Kind of related to #1026.

**Comment by przemyslawjacewicz** [comment]
For reference: fixing integration tests execution time in PR #1168 also reduced the number of partitions and emitted files. Accepting #1168 will also conclude this issue.
