### ISSUE TITLE
Export unmatched bibliographic references as Oaf entities

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1174]
We should export new entities representing bibliographic references which were not matched (e.g. not outcome of citation matching) with publications existing within OpenAIRE InformationSpace. Claudio has proposed the distinction between
* the complete bibref metadata (criteria are still to be defined) which could result in creation of `Publication` entity from 
* the lightweight `Citation` entity holding only the subset of metadata due to insufficient amount of details defined in bibliographic reference.

It would be a good idea to start with the assessment of the completeness of bibref metadata and the total volume so we could e.g. calculate the potential number of newly introduced entities (and the twice as much newly introduced relations). We could rely on  the `ExtractedDocumentMetadataMergedWithOriginal` records holding `references` field in this assessment process. This could be a hint on whether to include the thin "Citation" representation and what would be the expected growth of the InfoSpace graph and in future also the index size.

**Comment by marekhorst** [comment]
> It would be a good idea to start with the assessment of the completeness of bibref metadata and the total volume so we could e.g. calculate the potential number of newly introduced entities (and the twice as much newly introduced relations). We could rely on the `ExtractedDocumentMetadataMergedWithOriginal` records holding `references` field in this assessment process. This could be a hint on whether to include the thin "Citation" representation and what would be the expected growth of the InfoSpace graph and in future also the index size.

This was kind-of already done by me in:
https://issue.openaire.research-infrastructures.eu/issues/5973#note-4

**Comment by marekhorst** [comment]
Closing due to https://github.com/openaire/iis/issues/1175#issuecomment-748950831:

> After discussing the introduction of unmatched bibrefs representation in OA Graph with Claudio we came to conclusion it is better to put more effort into increasing the citation matching coverage rather than introducing new relations pointing to the new entities (rather thin representation of bibref entries) which will not be linked by anything else than the publication the bibref was extracted from.
