### ISSUE TITLE
Multiple organizations matched to one affiliation with high match strength

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1246]
This task is a subtask of parent task #1129 .

Article with id `50|dedup_wf_001::42330b7e2ea76d9fff4c9556fcb57f88` has only one affiliation extracted by CERMINE
```json
[
  {
    "organization": "Institute of Physics, M. Curie-Sklodowska University",
    "countryname": null,
    "countrycode": null,
    "address": "Radziszewskiego 10, Pl 20-031 Lublin",
    "rawtext": "Institute of Physics, M. Curie-Sklodowska University, Radziszewskiego 10, Pl 20-031 Lublin"
  }
]
```
This article is however matched to 7 organizations as shown by this join of affiliation matching results with organizations
```text
+--------------------+--------------------+-------------+--------------------+--------------------+--------------------+--------------+-----------+--------------------+
|          documentId|      organizationId|matchStrength|                  id|                name|           shortName|   countryName|countryCode|          websiteUrl|
+--------------------+--------------------+-------------+--------------------+--------------------+--------------------+--------------+-----------+--------------------+
|50|dedup_wf_001::...|20|dedup_wf_001::...|   0.99623805|20|dedup_wf_001::...|Institute of Physics|                 IPB|        Serbia|         RS|http://www.ipb.ac...|
|50|dedup_wf_001::...|20|dedup_wf_001::...|   0.99623805|20|dedup_wf_001::...|Institute of Physics|                 IOP|         India|         IN|http://www.iopb.r...|
|50|dedup_wf_001::...|20|anr_________::...|   0.99623805|20|anr_________::...|Institute of Physics|                null|       Unknown|    UNKNOWN|                null|
|50|dedup_wf_001::...|20|rcuk________::...|   0.99623805|20|rcuk________::...|Institute of Physics|                null|       Unknown|    UNKNOWN|                null|
|50|dedup_wf_001::...|20|nsf_________::...|   0.99623805|20|nsf_________::...|Institute of Physics|                null|    Yugoslavia|         YU|                null|
|50|dedup_wf_001::...|20|dedup_wf_001::...|   0.99623805|20|dedup_wf_001::...|Institute of Physics|                 IOP|United Kingdom|         GB| http://www.iop.org/|
|50|dedup_wf_001::...|20|grid________::...|   0.99955606|20|grid________::...|Institute of Physics|Institute of Physics|       Croatia|         HR|http://ifs2.ifs.h...|
+--------------------+--------------------+-------------+--------------------+--------------------+--------------------+--------------+-----------+--------------------+
```

We should check why multiple organizations are matched to this article with only a single affiliation. Affiliation matching module should produce a single organization matched to this affiliation. Taking above table we should have the last organization chosen because the match strength is the highest, apart from the fact that it is a wrong match.

Zeppelin note with data for this task is https://iis-cdh5-test-gw.ocean.icm.edu.pl/zeppelin/#/notebook/2FYP7MMK4 .

**Comment by przemyslawjacewicz** [comment]
Note: the case when a single affiliation is matched to multiple organizations is proper. Initial motivation was that there may be duplicates in organization datastore and an affiliation could be matched to duplicates of the 'same' affiliation. The right way of dealing with this situation is by assign lower match strength to each match.

**Comment by marekhorst** [comment]
> Note: the case when a single affiliation is matched to multiple organizations is proper. Initial motivation was that there may be duplicates in organization datastore and an affiliation could be matched to duplicates of the 'same' affiliation. The right way of dealing with this situation is by assign lower match strength to each match.

I'd say we should definitely lower match strength whenever we spot many variants of e.g. country name/code of matched organizations indicating we are matching with different organizations (like the case described in this ticket). Not necessarily when those fields are aligned for all matched organizations.

**Comment by przemyslawjacewicz** [comment]
For reference: just as in the case of #1244 the solution is to add the failing matching to quality test suite. This will lower the strengths assigned to the matches.
