### ISSUE TITLE
Align on the new persistent identifier creation strategy introduced in the Oaf model

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1251]
More details on the strategy itself is available on redmine issue ticket:
https://issue.openaire.research-infrastructures.eu/issues/6486

**Comment by przemyslawjacewicz** [comment]
Updates merged into temporary branch `przemyslawjacewicz_1251_1252_alignment_with_updates_in_oaf_model`. We should switch to released versions of dnet dependencies (after their release) and merge into master.
