### ISSUE TITLE
Align IIS with the recent updates in Oaf model related to the introduction of instance.alternateIdentifiers

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1252]
More details on the changes in Oaf model are available here:
https://issue.openaire.research-infrastructures.eu/issues/6487

**Comment by przemyslawjacewicz** [comment]
Updates merged into temporary branch przemyslawjacewicz_1251_1252_alignment_with_updates_in_oaf_model with this PR #1265 . We should switch to released versions of dnet dependencies (after their release) and merge into master.
