### ISSUE TITLE
Prepare Elsevier input for projects mining

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1263]
This task is #1214 follow up. Since we now know what text field should be propagated to projects mining:

https://issue.openaire.research-infrastructures.eu/issues/6396#note-8

we should focus on preparing simple transformation building `DocumentText` datastore. Once we have it we can simply run projects mining in isolation relying on Elsevier plaintexts and projects metadata taken from the last BETA or PROD provisioning round.

We should also update Elsevier input with all the newly acquired contents.

**Comment by przemyslawjacewicz** [comment]
The code for reading Elsevier data and `DocumentText` building is pushed to this branch [przemyslawjacewicz_1263_prepare_elsevier_input_for_project_mining](https://github.com/openaire/iis/tree/przemyslawjacewicz_1263_prepare_elsevier_input_for_project_mining). 

The mining was run and the results are available in Hive.

Separate ticket was also created for setting up automatic update of Elsevier input.
