### ISSUE TITLE
Align content identifiers with metadata record persistent identifiers

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1264]
More details on the changes in Oaf model are available here:
https://issue.openaire.research-infrastructures.eu/issues/6510

**Comment by marekhorst** [comment]
`transformers_idreplacer`, defined as one of the actions in `importer_content_url_chain` is responsible for identifiers translation in `DocumentContentUrl` records. Currently it relies on `input_id_mapping` datastore which currently provides original ids <-> dedup ids mappings so the content identifiers could be translated into deduplicated ones. 

I just checked and the `dedupmapping` datastore, provided by `importer_infospace`, and it seems it is only used in `importer_content_url_chain` subworkflow so we could simply replace the deduped ids with the persistent ids (for all the records, not only for the ones which were deduplicated) and this would be enough for the alignment. So the change should be applied on `ImportInformationSpaceJob`.

We could also rename the `dedupmapping` to more generic `identifiermapping` or something similar. Just to indicate we are not dealing with deduplication only.

Btw, I have updated the issue title to reflect the changes we are going to make in a better way.
