### ISSUE TITLE
Align InfoSpace importer with the recent updates in Oaf model related to the introduction of instance.alternateIdentifiers

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1272]
This is a supplement of #1251. We need to introduce changes in the InfoSpace importer module as well.

Long story short: we should avoid relying on the `Entity#pid` field (to be deprecated soon) and read identifiers from `Result#instance#pid` and `Instance#alternateIdentifiers` fields. Those sets are disjoint due to the phase run before mining but to be on a safe side we should treat `Result#instance#pid` as the more trustable than `Instance#alternateIdentifiers` just to make sure we have a specific non-random rule of picking the ids.

The following importer modules are relying on pids right now:
* `DatasetMetadataConverter`
* `DocumentMetadataConverter`

The full correspondence in the pid context is available in this slack thread:
https://openairegroup.slack.com/archives/C8VNGBV5E/p1620227883048300

**Comment by przemyslawjacewicz** [comment]
I've looked through the conversation and I think there's a small error in the description: we should avoid `Entity#pid` and move to `Result#instance#pid`, not `Result#pid`. @marekhorst Do you agree ?

**Comment by marekhorst** [comment]
Yes, just fixed the comment.
