### ISSUE TITLE
Modify JsonAvroTestUtils so it can work on records stored in multiple lines

### ISSUE THREAD

**Issue by madryk** [openaire/iis#131]
Now JsonAvroTestUtils.readJsonDataStore assumes that one record will be on one line.
We need to modify it so it can read objects stored in multiple lines.

Then modify json files in `/iis-workflows-citationmatching-direct/src/test/resources/eu/dnetlib/iis/workflows/citationmatching/direct/data` so they will be more human readable

**Comment by lukdumi** [comment]
Done in #113
