### ISSUE TITLE
Affiliation matching unit tests last far too long

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1329]
Apparently one of the long lasting tests, `AffOrgMatchVoterStrengthEstimatorAndTest`, was not marked with `@SlowTest` which makes this test to be run along with other unit tests instead of as a part of integration test suite which is executed nightly.

We should mark this test with `@SlowTest`.

**Comment by marekhorst** [comment]
`AffOrgMatchVoterStrengthEstimatorAndTest` exends `TestWithSharedSparkContext` which is already marked with `@SlowTest` so we should check why this test is still being run as a unit test.

**Comment by marekhorst** [comment]
It is directly related to already reported issue: #1193.

**Comment by marekhorst** [comment]
An issue related to introducing `@SlowTests`: https://github.com/openaire/iis/issues/1166

we should inspect why it is not being excluded from execution during the `test` phase.

**Comment by mpol** [comment]
So it seems the plan in #1166 was to exclude slow tests from standard builds.
Finally it was not done by default, but maybe we should use `-DotherExcludedGroups=SlowTest` in the IIS Jenkinsfile?

**Comment by marekhorst** [comment]
> So it seems the plan in #1166 was to exclude slow tests from standard builds.
> Finally it was not done by default, but maybe we should use `-DotherExcludedGroups=SlowTest` in the IIS Jenkinsfile?

Yes, this is the way to go.
