### ISSUE TITLE
DocumentTextCacheStorageUtilsTest breaks other tests if run at the wrong moment

### ISSUE THREAD

**Issue by mpol** [openaire/iis#1354]
Another case of tests interacting unexpectedly.

`DocumentTextCacheStorageUtilsTest` mocks Hadoop `Configuration` and when during one test
`DocumentTextCacheStorageUtils#storeInCache` throws an exception a `FileSystem` instance using
this mock is created and cached. Then later tests using `Filesystem#get` will get this mock-configured
filesystem from cache and likely fail - usually because it breaks checksumming configuration
by setting bytes per checksum to 0 (mocks return 0 from methods by default,
if we used Hadoop version with https://issues.apache.org/jira/browse/HADOOP-12831 fixed then I think
the test in `DocumentTextCacheStorageUtilsTest` would fail instead).

**Comment by mpol** [comment]
What to do?
- Don't mock the config,
- Make the mock better,
- Remove the mock-configured filesystem from the cache after the test - my current preference

**Comment by mpol** [comment]
@marekhorst what would you prefer here?

**Comment by marekhorst** [comment]
Maybe we should avoid reusing the mocks in subsequent tests by instantiating them for each individual test? Or perform the cleanup operation after each test, as you have suggested.

**Comment by marekhorst** [comment]
Is there a way to recreate this issue, because I am kind of clueless in which scenario the tests are being broken.

**Comment by mpol** [comment]
> Maybe we should avoid reusing the mocks in subsequent tests by instantiating them for each individual test? Or perform the cleanup operation after each test, as you have suggested.

It's not mock reuse that is a problem. It's that Hadoop's `FileSystem.get` caches the result so unrelated test in other class will get a not fully functional `FileSystem` instance from the cache without using any mocks.

**Comment by mpol** [comment]
> Is there a way to recreate this issue? Because I am kind of clueless in which scenario the tests are being broken.

I could not recreate it locally before I found out what is the problem so I did not try it, but using something (`ClassOrderer.OrderAnnotation`) from https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-classes to order `DocumentTextCacheStorageUtilsTest` very early should recreate the problem.

**Comment by mpol** [comment]
> I could not recreate it locally before I found out what is the problem so I did not try it, but using something (`ClassOrderer.OrderAnnotation`) from https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-execution-order-classes to order `DocumentTextCacheStorageUtilsTest` very early should recreate the problem.

Except that it requires a newer JUnit version :-/

**Comment by mpol** [comment]
We keep hitting these test interdependencies recently. Maybe it would be good to switch to fully random test ordering? It could mean some more unexpected test failures initially, but maybe it's worth it?

**Comment by marekhorst** [comment]
> We keep hitting these test interdependencies recently. Maybe it would be good to switch to fully random test ordering? It could mean some more unexpected test failures initially, but maybe it's worth it?

I guess I don't mind it. Let's check if we have any other unrevealed issues.
