### ISSUE TITLE
Introduce missing integration test cases for funders still not covered with tests

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1410]
While analyzing the missing ARC links case (#1395) we also get to know ARC funder was not covered with integration tests. Apparently this was the case for the funders integrated in the first batch of mining algos when adding the integration test case was not part of the mining module integration process.

After further inspection it turned out there were also [other funders](https://docs.google.com/spreadsheets/d/12bsSvXHC7qKmBj3wiIc9TZBCo9p7PK_8TzXnCAzRZsc/edit#gid=0) which should be covered, namely:

* FCT
* HRZZ
* MZOS
* NHMRC
* NSF
* SFI

We should add all the missing test cases to make sure we spot potential regression in mining algorithms accuracy.

**Comment by harry-di** [comment]
Thanks for looking into it, Marek
