### ISSUE TITLE
fix sentiment analysis precondition check typo

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#165]
Even though sentiment analysis is not integrated we do have integration test which fails after introducing invalid precondition check:
```
references.size() != sentiments.size()
```
we should check:
```
references.size() == sentiments.size()
```
instead.

**Comment by mkobos** [comment]
I wonder how this code that doesn't pass the integration test got into our code base. I guess you didn't run the integration test locally?

BTW, what is the address of our current CI server where I can check the status of the builds?

**Comment by marekhorst** [comment]
> I wonder how this code that doesn't pass the integration test got into our code base. I guess you didn't run the integration test locally?
> 
I guess the scenario was the following:
* I have introduced changes, run all the tests, created PR
* you have suggested to use precondition checks instead of `if` statements
* I have updated code and merged changes

Apparently I forgot to run integration tests again just before merging changes with master.

> BTW, what is the address of our current CI server where I can check the status of the builds?

ci.ceon.pl/view/IIS/

**Comment by mkobos** [comment]
Ok, thanks.

**Comment by mkobos** [comment]
BTW, I updated the wiki with new addresses of CI and artifactory
