### ISSUE TITLE
integrate croatian project mining

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#174]
Originally reported in:
https://issue.openaire.research-infrastructures.eu/issues/1511

We should update project reference extraction resources with the latest version from:
https://github.com/johnfouf/project_mining/commit/55c24ca57303a014b648274197aad6dccfb05a5d

**Comment by mkobos** [comment]
LGTM. 

I think that we should follow the practice described on wiki (section ["1.1 Adding OpenAIRE2020 project's partner code"](https://github.com/openaire/iis/wiki/Code-development-workflow#11-adding-openaire2020-projects-partner-code)) that we don't do code review of changes in the partner's code introduced by this partner. Please remember to set Ioannis as the author of the commit.
