### ISSUE TITLE
support JATS 2.3 XML format in both PMC metadata and plaintext ingesters

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#194]
This issue is related to integration of frontiers XML records described in details in openaire issue tracker:

[redmine:1660](https://issue.openaire.research-infrastructures.eu/issues/1660)

Records are compliant with JATS 2.3 format.

What is more: some of the EPMC records are also in JATS 2.3 format, not in JATS 1.0.

**Comment by marekhorst** [comment]
JATS 1.0 xsd: http://jats.nlm.nih.gov/publishing/1.0/xsd/JATS-journalpublishing1.xsd
JATS 2.3 xsd: http://dtd.nlm.nih.gov/publishing/2.3/xsd/journalpublishing.xsd

**Comment by marekhorst** [comment]
Major change will be related to `journal-title` element which is:
* nested in `journal-title-group` element [JATS 1.0]
* nested directly in `journal-meta` element [JATS 2.3]

All the other relevant differences (related to the fields we take into account) should be covered by current implementation. To make sure we need to introduce JATS 2.3 related unit tests.

**Comment by marekhorst** [comment]
Thanks. I've just pushed set of fixes related to `PmcXmlHandlerTest`.

**Comment by madryk** [comment]
I've checked it.
Ready to merge
