### ISSUE TITLE
Divide the module 'top' into two separate modules 'iis-wf-primary-workflow' and 'iis-wf-preprocess-workflow'

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#228]

**Comment by marekhorst** [comment]
Apart from creating dedicated maven modules for preprocessing and primary workflows the following changes, required to get rid of `iis-wf-top` module, will be made:
* moving `cache_builder` workflow to `iis-wf-metadataextraction` module
* moving `importer/content_url` workflow to `iis-wf-import` module
* moving `importer/plaintext/cached` workflow to `iis-wf-import` module
* moving `importer/plaintext/cached_by_checksum` workflow to `iis-wf-import` module
* moving `data/empty.json` to `iis-common` module
* moving importer integration test to `iis-wf-import` module (also requested in #279)
