### ISSUE TITLE
Fix missing src/test/resources directory issue in core-examples module after moving resources to src/main/

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#234]
The following error:

`[ERROR] Failed to execute goal org.apache.avro:avro-maven-plugin:1.7.4:schema (default) on project iis-workflows-core-examples: neither sourceDirectory: /home/azio/dnet-iis-git/iis-workflows/iis-workflows-core-examples/src/test/resources or testSourceDirectory: /home/azio/dnet-iis-git/iis-workflows/iis-workflows-core-examples/src/test/avro are directories`

appeared after moving all `resources` from `src/test` to `src/main` in #67. 

Apparently empty directory was created in my local system what satisfied build process but as it is empty directory it didn't get to git repository so CI system was missing `src/test/resources`.

**Comment by marekhorst** [comment]
The problem is caused by `avro-maven-plugin` execution defined in root `pom.xml` file.

The way to solve this issue is to disable this execution in `iis-workflows-core-examples` module by defining it as:
```
<execution>
    <phase>none</phase>
</execution>
```
This way we won't need to recreate empty `src/test/resources` directory.

**Comment by mpol** [comment]
I wonder why `sourceDirectory` and `outputDirectory` are used in the root pom to point at directories under `src/test` and not `testSourceDirectory` and `testOutputDirectory`.

**Comment by marekhorst** [comment]
Hmm, I don't recall the full context when it appeared. Maybe it was chosen due to the fact `iis-workfows-core-examples` oozie-package resources, including schemas, were defined in `test/resources`?

**Comment by marekhorst** [comment]
We should discuss this Tomorrow.

**Comment by mpol** [comment]
Actually avro-maven-plugin configuration could probably use a cleanup throughout the project, including documenting why and where default settings are not sufficient. We seem to have about four different places where the source directories are set, for example.

But this would be a separate task. @lukdumi

**Comment by marekhorst** [comment]
I have explored this issue and here is the conclusion:

### 1) `avro-maven-plugin`

It turned out there are 4 modules with `avro-maven-plugin` defined:
- `iis-wf-preprocessing`
- `iis-wf-referenceextraction`
- `iis-wf-metadataextraction`
- `iis-wf-citationmatching`

which do not have any avro schemas defined so we could drop redundant plugin definition.

Currently we do have shared configuration for this plugin in top `pom.xml` file in `pluginManagement` section. The problem is only 6 modules:
- `iis-3rdparty-avrojsoncoders`
- `iis-common`
- `iis-schemas`
- `iis-wf-collapsers`
- `iis-wf-core-examples`
- `iis-wf-primary`

out of almost 30 in total have avro schemas defined and only 3 of those 6 share the same configuration defined in top `pom.xml` file.

**Recommendation**: remove shared configuration in root `pom.xml` file and define it explicitly in 6 modules. This would allow avoiding #234 kind of issues we stuck on recently at least twice.

### 2) `build-helper-maven-plugin`

In some way it is bound to `avro-maven-plugin` because it attaches avro classes generated with `avro-maven-plugin` to build path.

It turned out there are 5 modules with `build-helper-maven-plugin` defined:
- `iis-wf-preprocessing`
- `iis-wf-referenceextraction`
- `iis-wf-metadataextraction`
- `iis-wf-citationmatching`
- `iis-wf-documentsclassification`

which do not have any avro schemas defined so we could drop redundant plugin definition.

Currently we do not have shared configuration for this plugin. It is defined explicitly in 6 modules out of almost 30.

**Recommendation**: Since it is bound to `avro-maven-plugin` - leave it as it is (apart from removing redundant plugin definitions).

**Comment by marekhorst** [comment]
@mpol before I move on with applying commit and creating pull request - what do you think about this solution?

**Comment by jlenotte** [comment]
I fixed this issue when I noticed that the avro folder where your schemas are **HAS** to be in `src/main/avro`, not `src/main/java/.../avro` or anywhere else. I kept the org.apache.avro execution phase to "generate-sources" phase and didn't have to use a "none" phase. Hope this helps.
