### ISSUE TITLE
Unresolvable documentsclassification input transformer

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#242]
I am unable to build package with `primary` workflow due to the following error:
```
eu.dnetlib.iis.primer.UnresolvableResourceException: Could not resolve eu/dnetlib/iis/workflows/documentsclassification/input_transformer/oozie_app
```

When I checked `documentsclassification` module resources I didn't find `input_transformer`.

Import file affected:
https://github.com/openaire/iis/blob/cdh5/iis-workflows/iis-workflows-top/src/main/resources/eu/dnetlib/iis/workflows/top/primary/processing/oozie_app/import.txt

**Comment by madryk** [comment]
It should be documentssimilarity
