### ISSUE TITLE
Deployment of new IIS version (master branch)

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#250]

**Comment by marekhorst** [comment]
Just deployed new IIS preprocessing and primary workflows on IIS cluster:
```
/lib/iis/preprocessing/snapshots/2016-03-16
/lib/iis/primary/snapshots/2016-03-16
```
Changelog available on [IIS versioning and deployment](https://issue.openaire.research-infrastructures.eu/projects/openaire/wiki/IIS_versioning_and_deployment) wiki page. Only the most important changes were listed.
