### ISSUE TITLE
Find the cause of the failing document classification int test

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#278]

**Comment by marekhorst** [comment]
I have just confirmed `documentsclassification/main/sampletest` integration test succeeded on IIS cluster by triggering test execution in "manual" mode:
```
mvn clean package -Pattach-test-resources,oozie-package,deploy,run -Dworkflow.source.dir=eu/dnetlib/iis/workflows/documentsclassification/main/sampletest -DiisConnectionProperties=/home/mhorst/.iis/application.properties.openaire
```
from `master` branch. Here is my `application.properties.openaire` content:
```
iis.hadoop.frontend.temp.dir=/mnt/tmp/marek.horst
iis.hadoop.frontend.user.name=marek.horst
iis.hadoop.frontend.host.name=gateway.hadoop.iis.openaire.eu
iis.hadoop.master.host.name=gateway.hadoop.iis.openaire.eu
iis.hadoop.frontend.port.ssh=22
oozieServiceLoc=http://gateway.hadoop.iis.openaire.eu:11000/oozie
nameNode=hdfs://iis-cluster-nn
jobTracker=iis-cluster-jt
oozie.execution.log.file.location=target/extract-and-run-on-remote-host.log
maven.executable=mvn
oozie.wf.validate.ForkJoin=false
```

The same integration test fails on our test cluster. You can find failing test details in jenkins:
http://ci.ceon.pl/view/IIS/job/iis_master_integration_tests/115/console

and on test cluster data node:
http://ci-test.hadoop.iis.openaire.eu:50060/tasklog?attemptid=attempt_201603200229_5785_m_000000_0&all=true

**Comment by marekhorst** [comment]
Original redmine thread related to upgrading documents classification algorithm and `apsw` library starts with:
https://issue.openaire.research-infrastructures.eu/issues/1212#note-64

**Comment by mpol** [comment]
I believe I've got it: http://ci-test.hadoop.iis.openaire.eu:50060/tasklog?attemptid=attempt_201603200229_6350_m_000000_0&all=true

After 95c77cd83e243191b3ebfdff948c1f867fa1079d `classify.sql` creates a `preclassifier` table in the database. Test cluster has only one node and there are two splits/mappers, so both try to access the same physical db concurrently - bad for SQLite. On production both mappers run on different nodes - no problem.

Probably making `preclassifiers` a temp table would help.

@marekhorst opinion?

**Comment by marekhorst** [comment]
Hmm, interesting.

I would expected attempt to be rerun (eventually fail after 3 retries) when error occurs unless... error is locked inside Madis world and not propagated to mapper, only logged. This way attempt is considered to end with successful result and the results it was intended to provide are missing. This could be the reason why we have 11 instead of 20  expected results in final output.

I guess we could confirm it by running job with limited number of concurrent mappers = 1.

**Comment by marekhorst** [comment]
> I guess we could confirm it by running job with limited number of concurrent mappers = 1.

It is not that straightforward in YARN as it was in MR1 (`mapred.map.tasks.maximum` property) but still possible:

http://blog.cloudera.com/blog/2014/04/apache-hadoop-yarn-avoiding-6-time-consuming-gotchas/

**Comment by marekhorst** [comment]
> It is not that straightforward in YARN as it was in MR1 (mapred.map.tasks.maximum property) but still possible

Just realized we are testing it on cdh4 cluster, so no YARN.

**Comment by marekhorst** [comment]
I've just invited johnfouf to our organization so we could discuss this issue with him in this thread.

**Comment by mpol** [comment]
`mexec.py -f cassify.sql` is run in `classify_documents.sh` on the left side of a pipeline, so indeed any errors from it are ignored and so the attempt is considered successful. A mapper failure here would be good to have.

**Comment by mpol** [comment]
Actually the only property that seems to have made a difference is `mapred.min.split.size` - but finally I managed to run the test with a single mapper on the test cluster and it passed.

**Comment by mpol** [comment]
Ioannis agrees that making `preclassifiers` a temp table would help: https://issue.openaire.research-infrastructures.eu/issues/1212#note-75
