### ISSUE TITLE
Built-in AvroStorage causes "Can't redefine: authors" pig error when manipulating data in cache

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#285]
Since replacing piggybank version of `AvroStorage` with built-in one in #265 all cache manipulating PIG scripts throw:
```
ERROR 2116: Can't redefine: authors
```
error when writing avro datastore containing [ExtractedDocumentMetadata](https://github.com/openaire/iis/blob/5c090408fa5d89fd1a68223c1db8af715e09526f/iis-schemas/src/main/resources/eu/dnetlib/iis/metadataextraction/ExtractedDocumentMetadata.avdl) records.

It seems it is related to `authors` field name ambiguity and I assume the following fields are causing this problem:
- `ExtractedDocumentMetadata#authors`
- `ExtractedDocumentMetadata#references#basicMetadata#authors`

I didn't find any other candidates.

I am not sure why pig consider this as a problem, probably data modelling on pig layer is unaware of field record inheritance and this is when the error occurs. `piggybank` didn't have problem with this anyway.

If we are going to fix this simply by renaming one of the fields we will be forced to regenerate cache from scratch. But it seems this problem affects cdh5 branch only so this shouldn't be major problem since large cache was generated only on cdh4 cluster. We can sacrifice cdh5 cache.

**Comment by madryk** [comment]
I've had the same error - it should not affect existing datastores; they will be read/written as always.
Problem lays rather in translating pig schema to avro schema.
There will be needed correction in pig scripts.
