### ISSUE TITLE
Built-in AvroStorage claims 'Pig Schema contains a name that is not allowed in Avro'

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#286]
Since replacing `piggybank` version of `AvroStorage` with built-in one in #265 `replacer_1_field.pig` script of `idreplacer` transformer module claims:

`Pig Schema contains a name that is not allowed in Avro`. 

It's a pity it doesn't point out which name is not allowed.

Detailed info available here:
http://spark-m1.vls.icm.edu.pl:19888/jobhistory/logs/spark-s3.vls.icm.edu.pl:50146/container_e133_1448443717056_6399_01_000001/job_1448443717056_6399/mhorst/stderr/?start=0

Schema under suspicion: [DocumentContentUrl](https://github.com/openaire/iis/blob/5c090408fa5d89fd1a68223c1db8af715e09526f/iis-schemas/src/main/resources/eu/dnetlib/iis/importer/auxiliary/DocumentContentUrl.avdl)

Again, `piggybank` `AvroStorage` didn't have problem with this schema.

**Comment by madryk** [comment]
When we look in pig schema for output in this pig script, there is a lot of field names like:
`eu.dnetlib.iis.common.pig.udfs.idreplacerudf_main::journal_7::main::id: chararray,`
AvroStorage complains about dots in field names.
Probably we will have to update/correct  IdReplacerUDF
