### ISSUE TITLE
Primary processing integration test fails at document_classification_job

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#287]
with the following error:
```
java.lang.NoSuchMethodError: org.apache.hadoop.mapred.TaskLog.createLogSyncer()Ljava/util/concurrent/ScheduledExecutorService;
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.<init>(MRAppMaster.java:244)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.<init>(MRAppMaster.java:227)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1412)
```
Link to spark job:
http://spark-m1.vls.icm.edu.pl:23188/cluster/app/application_1448443717056_6544/

**Comment by madryk** [comment]
It looks like we have two some hadoop libraries in different versions (one on cluster and one in oozie package)

**Comment by madryk** [comment]
Fixed in different issue.
Problem was with library hadoop-core that was included in oozie-package

**Comment by lakshmanas** [comment]
I am facing the same issue. I am trying to tigger a spark job from oozie workflow, using Cloudera hadoop version 5.4.5 with spark 1.3 and oozie client version 4.1.0-cdh5.4.5. I can't figure out which hadoop core lib is getting picked and how. Can you pleas help me on how to fix this ?
