### ISSUE TITLE
Prepare IS metadata dump

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#298]

**Comment by marekhorst** [comment]
@mkobos please find latest organizations dump in:
https://box.openaire.eu/index.php/s/shywgJsv6HAjWYH

Affiliations are generated by IIS at this very moment, should be available in few hours.

**Comment by mkobos** [comment]
Thanks. I analyzed the organizations dump and shared the analysis along with some questions on Redmine (https://issue.openaire.research-infrastructures.eu/issues/1977#note-19)

**Comment by marekhorst** [comment]
All production packages uploaded to `/mnt/srv-nfs/oa-dm/2016-04-06/production/`.
