### ISSUE TITLE
Create integration test for transformers/metadataextraction/skip_extracted

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#306]
It can be based on newly created:

https://github.com/openaire/iis/tree/e5af8bb49d0b932810c0c8f4eef780ce55e56266/iis-wf/iis-wf-transformers/src/test/resources/eu/dnetlib/iis/wf/transformers/metadataextraction/skip_extracted_without_meta

**Comment by lukdumi** [comment]
Marek, please, use capital letters at the beginning of the issue title.

**Comment by marekhorst** [comment]
> Marek, please, use capital letters at the beginning of the issue title.

OK, fixed. It's so hard to fight habits.
