### ISSUE TITLE
Build system fails due to CermineAffiliation methods limited visibility

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#307]
Here is the link to jenkins build log:
http://ci.ceon.pl/job/iis_cdh5_build/241/console

I guess setter methods should be public while accessing them in different package.

**Comment by marekhorst** [comment]
@lukdumi can you look into this issue? If I recall correctly you were working on `CermineAffiliation` recently so you probably know better how to fix this.

**Comment by lukdumi** [comment]
I've corrected it and pushed immediately, as the correction has been really small and only in one test.
