### ISSUE TITLE
referenceextraction_dataset_main_sqlite_sampletest fails

### ISSUE THREAD

**Issue by mpol** [openaire/iis#308]
Seems related to #269 in that the tests use the same expected data and this one apparently still produces what was expected before the change.

Is the inconsistency between the two tests expected?

http://ci-test.hadoop.iis.openaire.eu:50030/jobdetails.jsp?jobid=job_201603200229_9413

```
Expected records:
{
  "documentId": "WOS:000316614600026",
  "datasetId": "oai:oai.datacite.org:1390724",
  "confidenceLevel": 0.8164966
}
{
  "documentId": "WOS:000316614600034",
  "datasetId": "oai:oai.datacite.org:1457141",
  "confidenceLevel": 0.74386376
}


Actual records:
{
  "documentId": "WOS:000316614600026",
  "datasetId": "oai:oai.datacite.org:1390724",
  "confidenceLevel": 0.8164966
}
{
  "documentId": "WOS:000316614600034",
  "datasetId": "oai:oai.datacite.org:1457141",
  "confidenceLevel": 0.66332495
}
```

**Comment by mpol** [comment]
@marekhorst Is the inconsistency between the two tests a problem? Or should we simply separate the expected data and be done with it?

**Comment by marekhorst** [comment]
In short: let's split it. 

`main_sqlite` tests only second phase of reference extraction algorithm (of two in total) - finding references using sqlite db. 

Database creation is the first phase and it is mocked by java `DatasetDBProducer` in this test. `apsw` upgrade affected db creation subpart, this is why this test did not fail after `apsw` upgrade as db is static and provided by java class.
