### ISSUE TITLE
Create SequenceFileTextValueReader unit test

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#364]
The following class:

https://github.com/openaire/iis/blob/cdh5/iis-common/src/main/java/eu/dnetlib/iis/common/java/io/SequenceFileTextValueReader.java

is missing unit test.

First we need to decide whether we are able to create one since this reader is rooted into hadoop filesystem (`FileSystem` and `Reader` classes).

**Comment by lukdumi** [comment]
Marek, again, please use capital letters at the beginnings of issue subjects.
