### ISSUE TITLE
Improve the way IIS is configured to distcp outcome to DM HA cluster

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#418]
According to: #408

**Comment by marekhorst** [comment]
Paweł deployed namenode proxy on DM cluster which simplifies final solution:
```
hdfs://namenode.hadoop.dm.openaire.eu
```
Having proxy dispatching requests to active namenode we don't have to introduce any changes in IIS.

More details can be found in redmine [#2111](https://issue.openaire.research-infrastructures.eu/issues/2111).
