### ISSUE TITLE
Adjust documents similarity related parameters to the new cluster environment

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#428]
Up until now `documents similarity` algorithm was adjusted to the IIS cluster configuration:
http://baszta.icm.edu.pl/wiki/OpenAIREplus/Hadoop/IIS

Two parameters were set:
```
ds_parallel=20
ds_mapredChildJavaOpts=Xmx20g
```
where:
* `ds_parallel` - the number of reduce tasks for the MapReduce jobs generated by Pig
* `ds_mapredChildJavaOpts` - used in Pig both map and reduce phases

Both parameters should be adjusted to the new OCEAN's cluster configuration.

**Comment by marekhorst** [comment]
> ds_mapredChildJavaOpts=Xmx20g

Notice: according to:

https://mantis.icm.edu.pl/view.php?id=9621#c30841

yarn is configured in the following way:
```
* yarn.nodemanager.resource.memory-mb=96GB
* yarn.nodemanager.resource.cpu-vcores=12
* mapreduce.map.memory.mb=6GB
* mapreduce.map.cpu.vcores=1
* mapreduce.reduce.memory.mb=8GB
* mapreduce.reduce.cpu.vcores=1
```
We need to get below `mapreduce.[map/reduce].memory.mb` threshold or we end up with:
```
Container [...] is running beyond physical memory limits.
```
kind of errors.

Now if `documents similarity` algorithm does not fail on cluster - this means it also does not require `Xmx20g` to be set so we could change it hopefully getting below yarn threshold. 

If it fails - we would need to either change yarn memory configuration (not recommended since this will affect max number of concurrent map/reduce tasks) or find the way to keep it low, possibly by manipulating other parameters.

**Comment by mpol** [comment]
In tests on 18.5G input data the workflow passes within current memory limits.

**Comment by mpol** [comment]
Setting `parallel` to more than 20 reduces processing time slightly, but the gains aren't very high:

- 20 - 135 minutes
- 40 - 108 minutes
- 80 - 95 minutes
