### ISSUE TITLE
Affiliation matching fails on large input

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#463]
Link to failed oozie job:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:11000/oozie/?job=0000375-160603093332521-oozie-oozi-W

Link to spark summary:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:18088/history/application_1464942752091_1226/1/jobs/

**Comment by lukdumi** [comment]
http://iis-cdh5-test-m2.ocean.icm.edu.pl:8088/cluster/app/application_1464942752091_1226

User class threw exception: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory /user/marek.horst/wf/primary/main/working_dir/exported/matched_affiliation already exists
