### ISSUE TITLE
Gather properties that should be reported during the run of IIS

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#511]

**Comment by marekhorst** [comment]
Counters for data imported from DNet: 
 - datasets
 - InfoSpace meta
    - `docmeta`
    - `docproj`
    - `organization`
    - `person`
    - `project`
    - `projectorg`
 - project concepts
 - imported contents by type
    - `pdf`
    - `xml`
    - `html`
    - `plaintext`
    - `file::WoS`
 - `ExtractedDocumentMetadata` records
    - retrieved from metadataextraction cache
    - provided by pmc ingestion
 - faults
    - pmc
    - cermine

Counters for data processed by IIS: 
 - document texts extracted from `ExtractedDocumentMetadata` records (direct input to all referenceextraction algorithms)
 - projects after filtering by `${referenceextraction_project_fundingclass_blacklist_regex}` (optional, filtering is rarely used)

Counters for data exported by IIS: 
 - matched citations 
    - total (do not confuse with number of publications for which citations were matched, this could be measured with different counter)
    - number of extracted citation texts (this could be also measured at importing phase)
    - number of publications with extracted citations texts (at least one bibref)
 - document similarities
 - documents classification
     - number of classified publications
     - aggregated number of associated classes for each taxonomy (`arxiv`, `WoS`, `DDC`, `meshEuroPMC`, `ACM`) 
 - dataset references
 - project references
 - project concepts references
     - number of publications with at least one reference
     - total number of references
 - PDB references
     - number of publications with at least one reference
     - total number of references
 - research initiative references
     - number of publications with at least one reference
     - total number of references
 - software url references
     - number of publications with at least one reference
     - total number of references
 - matched affiliations
     - number of publications with at least one match
     - total number of matched organizations

**Comment by madryk** [comment]
I would add:
<ul>
<li>imported contents by type (pdf, xml, html, plaintext, file::WoS) - how many records was rejected (too big filesize, etc.)</li>
<li>matched affiliations</li>
<ul>
<li>total number of affiliations</li>
<li>total number of affiliations with at least one match</li>
</ul>
</ul>

**Comment by marekhorst** [comment]
One other idea I would like to throw in: it will be nice to know the inference modules execution time. 

It is already possible to access this information from oozie web page by clicking into subworkflows etc but it will be nice to have it in some summary generated by IIS. This would simplify execution time comparison for different IIS runs and track changes.
