### ISSUE TITLE
Move the cluster specific settings (numExecutors etc) to external properties

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#512]

**Comment by marekhorst** [comment]
The following spark related properties were introduced in top level primary workflow:

top level property name | default value
--- | ---
`affiliationmatchingSparkExecutorMemory` | `6g`
`affiliationmatchingSparkExecutorCores` | `1`
`affiliationmatchingSparkNumExecutors` | `64`
`affiliationmatchingSparkDriverMemory` | `2g`
`affiliationmatchingSparkDriverOverhead` | `513`
`citationmatchingDirectSparkExecutorMemory` | `7g`
`citationmatchingDirectSparkExecutorCores` | `1`
`citationmatchingDirectSparkNumExecutors` | `200`
`citationmatchingFuzzySparkExecutorMemory` | `7g`
`citationmatchingFuzzySparkExecutorCores` | `1`
`citationmatchingFuzzySparkNumExecutors` | `200`
`citationmatchingFuzzyNumberOfPartitions` | `400`

which are mapped to inner workflow properties where default values were removed.

All listed properties can be easily overridden in external `config-default.xml` configuration file placed next to the top level oozie workflow definition.
