### ISSUE TITLE
Affiliation matching is failing due to running beyond physical memory limits

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#522]
I just triggered most recent version of affmatch and apparently we need to adjust memory configuration again:

```
Application application_1464942752091_2894 failed 2 times due to AM Container for appattempt_1464942752091_2894_000002 exited with exitCode: -104
For more detailed output, check application tracking page:http://iis-cdh5-test-m2.ocean.icm.edu.pl:8088/proxy/application_1464942752091_2894/Then, click on links to logs of each attempt.
Diagnostics: Container [pid=47288,containerID=container_e29_1464942752091_2894_02_000001] is running beyond physical memory limits. Current usage: 1.6 GB of 1.5 GB physical memory used; 3.5 GB of 3.1 GB virtual memory used. Killing container.
```

Here is the link to log file:
http://iis-cdh5-test-m2.ocean.icm.edu.pl:8088/cluster/app/application_1464942752091_2894

**Comment by marekhorst** [comment]
I've just preserved whole `primary` workflow working directory in:
```
/tmp/primary/working_dir_20160622
```
which includes affmatch input:
```
input_document_metadata=/tmp/primary/working_dir_20160622/primary_import/extracted_document_metadata
input_organizations=/tmp/primary/working_dir_20160622/primary_import/metadataimport/organization
input_document_to_project=/tmp/primary/working_dir_20160622/primary_import/metadataimport/docproject
input_inferred_document_to_project=/tmp/primary/working_dir_20160622/exported/document_to_project
input_project_to_organization=/tmp/primary/working_dir_20160622/primary_import/metadataimport/projectorg
```

**Comment by madryk** [comment]
I have run affmatching workfow but with my data and it also failed:
http://iis-cdh5-test-m2.ocean.icm.edu.pl:8088/cluster/app/application_1464942752091_3037
On the second try I added `--driver-memory 6G` to spark-opts and it succeeded.
Don't know why though.
http://iis-cdh5-test-m2.ocean.icm.edu.pl:8088/cluster/app/application_1464942752091_3042

**Comment by mpol** [comment]
We can either add the setting to the workflow (and override it for tests) or pester Paweł to change the cluster default.
