### ISSUE TITLE
Omit the provided libs during creation of oozie test package

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#56]

**Comment by madryk** [comment]
Sizes of oozie package for different projects:

iis-workflows-core-examples (without attached tests): 8.9MB
iis-workflows-core-examples (with attached tests): 96.7MB

iis-workflows-citationmatching (without attached tests): 251.5MB
iis-workflows-citationmatching (with attached tests): 269.4MB

iis-workflows-collapsers (without attached tests): 57.8MB
iis-workflows-collapsers (with attached tests): 74.5MB

iis-workflows-referenceextraction (without attached tests): 45.1MB
iis-workflows-referenceextraction (with attached tests): 59.6MB

iis-workflows-top (without attached tests): 419.9MB
iis-workflows-top (with attached tests): 442MB
