### ISSUE TITLE
Remove unused workflows in iis-wf-import module

### ISSUE THREAD

**Issue by madryk** [openaire/iis#573]
It seems that workflows:
`/iis-wf-import/src/main/resources/eu/dnetlib/iis/wf/importer/plaintext/cached/oozie_app/workflow.xml`
`/iis-wf-import/src/main/resources/eu/dnetlib/iis/wf/importer/plaintext/cached_by_checksum/oozie_app/workflow.xml`
`/iis-wf-import/src/main/resources/eu/dnetlib/iis/wf/importer/plaintext/process/oozie_app/workflow.xml`
`/iis-wf-import/src/main/resources/eu/dnetlib/iis/wf/importer/vocabulary/oozie_app/workflow.xml`
are not used from our main workflows - `primary`, `preprocessing` and `cache_builder`.
We probably should remove them.
The most problematic from above is `importer/plaintext/cached_by_checksum` as it tries to import non existent workflow

**Comment by marekhorst** [comment]
> `/iis-wf-import/src/main/resources/eu/dnetlib/iis/wf/importer/vocabulary/oozie_app/workflow.xml`

This one will be removed after merging #576 changes.
