### ISSUE TITLE
Correct ssh commands to conform to bash-3.2 on OS X

### ISSUE THREAD

**Issue by miconi** [openaire/iis#766]
The following error appears:

```
17/03/14 11:30:32 INFO MavenTestWorkflowRunner: [INFO] --- exec-maven-plugin:1.5.0:exec (create-target-dir) @ iis-wf-affmatching ---
17/03/14 11:30:33 INFO MavenTestWorkflowRunner: [ERROR] Command execution failed.
17/03/14 11:30:33 INFO MavenTestWorkflowRunner: org.apache.commons.exec.ExecuteException: Process exited with an error: 255 (Exit value: 255)
```

when integration tests are run with `mvn verify` command.

This happens because `ssh` command line arguments are parsed differently in different versions of bash (possibly that bug occurs only on OS X).

For example such command is constructed:

    ssh USERNAME@iis-ci-test.ocean.icm.edu.pl -p 22 -o StrictHostKeyChecking=no rm -rf /home/USERNAME/oozie-packages/sandboxName/output/; mkdir -p /home/USERNAME/oozie-packages/sandboxName/output/

which is wrong, because the semicolon is treated as the end of the whole command, not the command that should be executed remotely (i.e. the parameter to the `ssh` command).

**Comment by marekhorst** [comment]
We have eliminated `ssh` command line arguments as source of the problem.

Even though you have managed to bypass this problem is there anything we could improve in IIS to make it more compliant with OSX environment?
