### ISSUE TITLE
jython dependency not provided in CDH5 environment

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#80]
IIS execution fails in CDH5 environment with the following error:

`Error: java.lang.ClassNotFoundException: org.python.google.common.collect.Lists`

at: [OriginConfidenceMergingCollapser](https://github.com/openaire/iis/blob/b4efb94ca687d44cad88fb39061f0a2c685db735/iis-workflows/iis-workflows-collapsers/src/main/java/eu/dnetlib/iis/workflows/collapsers/origins/OriginConfidenceMergingCollapser.java).

Mentioned class is part of jython library which is not explicitly listed among `iis-workflows-collapsers` dependencies but provided implicitly by `pig` dependency.

Since this class is required by `iis-workflows-collapsers` it should be explicitly listed among dependencies.

Besides, do we really need to introduce jython dependency only to obtain singleton list by executing `Lists.newArrayList()`? I've searched `iis-workflows-collapsers` sources by `org.python` package and this was the only context dependency was used. 
Couldn't we simply use java embedded `Collections.singletonList()` or guava's [Lists.newArrayList()](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Lists.html)? I've got this impression `org.python.google.common.collect.Lists` was picked accidentally.

**Comment by dtkaczyk** [comment]
Yes, it looks like a mistake. I must have accidentally chose to add the wrong package to import.
It should be enough to change org.python.google.common.collect.Lists package to com.google.common.collect.Lists. The code will remain the same.
Would you do it, if you have the code checked out and ready for editing? Or do you want me to do it?

**Comment by marekhorst** [comment]
Sure, I will apply this change, just wanted to make sure my impression was valid.
