### ISSUE TITLE
Sentiment analysis module fails to report status for 600 seconds

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#90]
I've just come across strange issue with sentiment analysis module while processing bibliographic references from EuropePMC resources:
```
Task attempt_201510221516_1306_m_000031_2 failed to report status for 600 seconds. Killing!
```
ultimately interrupting whole processing.

This indicates some performance issues with current mock implementation of sentiment analysis:

https://github.com/openaire/iis/blob/marekhorst_%231443_citation_sentiment_analysis_integration/iis-workflows/iis-workflows-sentimentanalysis/src/main/java/eu/dnetlib/iis/workflows/sentimentanalysis/SentimentAnalyzer.java

Do you have any suspicion of what could be the reason? What is the most time consuming part of current sentiment analysis implementation?

**Comment by marekhorst** [comment]
I've processed puma contents before - no such problem occurred. But this was very small repository with ~9k publications.

**Comment by lukdumi** [comment]
Sentiments analysis module has been removed from iis.
