### ISSUE TITLE
introduce projects blacklisting before project reference extraction

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#96]
Request was originally reported by Alessia in:
https://issue.openaire.research-infrastructures.eu/issues/1549

In order to filter out H2020 projects in a generic way we should introduce projects blacklisting by `funding class` field. 

New input parameter should be supported, e.g. `import_project_fundingclass_blacklist`, (set to `$UNDEFINED$` value by default) conveying regular expression filtering out all the projects which should not be matched against publications by project reference extraction algorithm.

We should decide whether filtering should be performed during projects importing phase, which will cause blacklisted projects will not enter IIS at all, or just before projects reference extraction - filtering will be applied on `eu.dnetlib.iis.importer.schemas.Project` avro datastore. Currently projects are utilized only by project reference extraction algorithm but this could change in future.

**Comment by marekhorst** [comment]
[ProjectDBBuilder.java](https://github.com/openaire/iis/blob/b4efb94ca687d44cad88fb39061f0a2c685db735/iis-workflows/iis-workflows-referenceextraction/src/main/java/eu/dnetlib/iis/workflows/referenceextraction/project/ProjectDBBuilder.java) could be the right place to perform filtering in. We are iterating over `Project` entries in order to put them into `SQLite` database provided as input to project reference extraction algorithm.

**Comment by marekhorst** [comment]
> We should decide whether filtering should be performed during projects importing phase, which will cause blacklisted projects will not enter IIS at all, or just before projects reference extraction - filtering will be applied on eu.dnetlib.iis.importer.schemas.Project avro datastore. Currently projects are utilized only by project reference extraction algorithm but this could change in future.

@mkobos what do you think? Should we perform filtering on global IIS level or only in project reference extraction context?

**Comment by mkobos** [comment]
> ProjectDBBuilder.java could be the right place to perform filtering in. We are iterating over Project entries here in order to put them into SQLite database which in the next step is provided as input to project reference extraction algorithm.

I'm not sure if it's such a good idea. The code of [ProjectDBBuilder.java][1] seems to be very generic, i.e. it doesn't really know anything about the structure of the processed data. By doing the filtering here we would embed such a knowledge in this code. I think that it might be better to create a separate Oozie action that would do the filtering before calling the ProjecctDBBuilder.

[1]: https://github.com/openaire/iis/blob/b4efb94ca687d44cad88fb39061f0a2c685db735/iis-workflows/iis-workflows-referenceextraction/src/main/java/eu/dnetlib/iis/workflows/referenceextraction/project/ProjectDBBuilder.java

>> We should decide whether filtering should be performed during projects importing phase, which will cause blacklisted projects will not enter IIS at all, or just before projects reference extraction - filtering will be applied on eu.dnetlib.iis.importer.schemas.Project avro datastore. Currently projects are utilized only by project reference extraction algorithm but this could change in future.
> 
> @mkobos what do you think? Should we perform filtering on global IIS level or only in project reference extraction context?

I don't know: What are the use-cases? What does the user expect (i.e. Info Space)? The Redmine ticket that you reference here is soooo long and this discourages me from diving into details of it very effectively :)

**Comment by marekhorst** [comment]
> I'm not sure if it's such a good idea. The code of ProjectDBBuilder.java seems to be very generic, i.e. it doesn't really know anything about the structure of the processed data. By doing the filtering here we would embed such a knowledge in this code. I think that it might be better to create a separate Oozie action that would do the filtering before calling the ProjecctDBBuilder.

I thought about some dedicated filter initially but I found it more complex and time consuming (preparing dedicated transformer module along with integration tests, extending workflow with another action etc) so I picked easier solution. I wouldn't say `ProjectDBBuilder` is generic since it explicitly iterates over `Project` records. Although it's true we do not inspect its contents right now.

> I don't know: What are the use-cases? What does the user expect (i.e. Info Space)? The Redmine ticket that you reference here is soooo long and this discourages me from diving into details of it very effectively :)

The use case is we want to exclude some projects (H2020 in particular) from reference extraction mainly due to false positives. We do not want to introduce them on production until algorithm is refined.

We could do this either way: at importing phase or just before executing mentioned algorithm. When doing it at importing phase we make whole IIS unaware of some subset of projects which were filtered out. The only context projects are used is finding referenced projects in publications. On the other hand the only reason we are required to filter out projects is reference extraction algorithm deficiency. This is why I tend more to perform filtering just before project reference extraction.

**Comment by mkobos** [comment]
> > I'm not sure if it's such a good idea. The code of ProjectDBBuilder.java seems to be very generic, i.e. it doesn't really know anything about the structure of the processed data. By doing the filtering here we would embed such a knowledge in this code. I think that it might be better to create a separate Oozie action that would do the filtering before calling the ProjecctDBBuilder.
> 
> I thought about some dedicated filter initially but I found it more complex and time consuming (preparing dedicated transformer module along with integration tests, extending workflow with another action etc) so I picked easier solution. 

Ok. I guess that the problem is that extending Oozie workflows is tedious. I imagine that if we were using Spark, this would be much easier.

> I wouldn't say ProjectDBBuilder is generic since it explicitly iterates over Project records. Although it's true we do not inspect its contents right now.

Yeah, that's what I meant - it doesn't care about the contents of these records, so in principle it might be possible to make the code truly generic so the code doesn't know what structure exactly it processes.

> > I don't know: What are the use-cases? What does the user expect (i.e. Info Space)? The Redmine ticket that you reference here is soooo long and this discourages me from diving into details of it very effectively :)
> 
> The use case is we want to exclude some projects (H2020 in particular) from reference extraction mainly due to false positives. We do not want to introduce them on production until algorithm is refined.
> 
> We could do this either way: at importing phase or just before executing mentioned algorithm. When doing it at importing phase we make whole IIS unaware of some subset of projects which were filtered out. The only context projects are used is finding referenced projects in publications. On the other hand the only reason we are required to filter out projects is reference extraction algorithm deficiency. This is why I tend more to perform filtering just before project reference extraction.

I get it now and agree. Since we want to implement a workaround for problems with the project extraction module, it should be placed in the vicinity of the module.

PS That `r` keyboard shortcut is magic :-)
